// src/components/NosMateriels.vue
<template>
  <div class="page">
    <header class="header">
      <div class="logo-section">
        <img src="../assets/logo.jpg" alt="Logo" class="logo" />
        <h1 class="site-title">Reve d’ un Jour</h1>
      </div>
      <div class="nav-buttons">
        <router-link to="/NosOffres" class="btn-nav">Nos offres</router-link>
        <router-link to="/NosMateriels" class="btn-nav">Nos matériels</router-link>
      </div>
    </header>

    <main class="content">
      <h2 class="section-title">CHOISISSEZ VOTRE MATERIEL POUR L'ÉVÉNEMENT</h2>
      <p class="subtitle">Sélectionnez les équipements que vous souhaitez utiliser ce jour-là :</p>

      <div class="materiels">
        <div v-for="(materiel, i) in materiels" :key="i" class="materiel-card">
          <img :src="materiel.image" alt="Matériel" class="materiel-image" />
          <div class="materiel-info">
            <p><b>Nom :</b> {{ materiel.nom }}</p>
            <p><b>Description :</b> {{ materiel.description }}</p>
            <p><b>Prix :</b> {{ materiel.prix }} Ar</p>

            <div class="quantity">
              <button @click="decrement(materiel)">−</button>
              <input type="number" v-model="materiel.qteChoisie" min="0" :max="materiel.quantite" readonly />
              <button @click="increment(materiel)">+</button>
            </div>

            <p><b>Disponible :</b> {{ materiel.quantite }}</p>

            <button
              class="btn-action"
              :class="{ selected: materiel.selectionne }"
              @click="selectionner(materiel)"
            >
              {{ materiel.selectionne ? "Sélectionné ✅" : "Sélectionner" }}
            </button>
          </div>
        </div>
      </div>

      <div class="actions">
        <button class="btn-valid" @click="valider">Validé</button>
        <button class="btn-cancel" @click="annuler">Annuler</button>
      </div>

      <router-link to="/" class="btn-logout">Se deconnecter</router-link>
    </main>

    <footer class="footer">
      <p>📞 038 43 332 25</p>
      <p>📘 Stéphanya VELOHASIMALALA</p>
    </footer>
  </div>
</template>

<script setup>
import { ref } from "vue";
import { useRouter } from "vue-router";

const router = useRouter();

const materiels = ref([
  {
    nom: "Microphone sans fil professionnel",
    description: "Micro haute qualité adapté aux conférences et fêtes",
    prix: "10 000",
    quantite: 10,
    qteChoisie: 0,
    selectionne: false,
    image: new URL("../assets/micro.jpg", import.meta.url).href,
  },
  {
    nom: "Chaises blanches harmonieuses",
    description: "Confortables, idéales pour mariage et réception",
    prix: "2 000",
    quantite: 400,
    qteChoisie: 0,
    selectionne: false,
    image: new URL("../assets/chaise.jpg", import.meta.url).href,
  },
  {
    nom: "Table ronde et 6 places",
    description: "Tables élégantes, style dégagé",
    prix: "4 000",
    quantite: 200,
    qteChoisie: 0,
    selectionne: false,
    image: new URL("../assets/table.jpg", import.meta.url).href,
  },
  {
    nom: "Sonorisation complète",
    description: "Enceintes, mixeur, micro, tout le nécessaire musical",
    prix: "50 000",
    quantite: 5,
    qteChoisie: 0,
    selectionne: false,
    image: new URL("../assets/sono.jpg", import.meta.url).href,
  },
]);

function increment(m) {
  if (m.qteChoisie < m.quantite) m.qteChoisie++;
}

function decrement(m) {
  if (m.qteChoisie > 0) m.qteChoisie--;
}

function selectionner(m) {
  m.selectionne = !m.selectionne;
}

function valider() {
  const choisis = materiels.value.filter((m) => m.selectionne && m.qteChoisie > 0);

  if (choisis.length === 0) {
    alert("Veuillez choisir au moins un matériel avec quantité > 0 !");
    return;
  }

  // ✅ Stocker dans localStorage
  localStorage.setItem("materielsSelectionnes", JSON.stringify(choisis));

  // ✅ Aller à la page réservation
  router.push("/Reservation");
}

function annuler() {
  materiels.value.forEach((m) => {
    m.selectionne = false;
    m.qteChoisie = 0;
  });
  alert("❌ Sélections annulées.");
}
</script>
<style scoped>
.page {
  background: #fff9e9;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
}
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 90%;
  margin: 20px auto;
}
.logo-section {
  display: flex;
  align-items: center;
  gap: 10px;
}

.logo {
  width: 50px;
  height: 50px;
  border-radius: 50%;
}
.site-title {
  color: #d93025;
  font-weight: bold;
  font-size: 20px;
}
.nav-buttons {
  display: flex;
  gap: 10px;
}
.btn-nav {
  background: #a6d785;
  padding: 8px 15px;
  border-radius: 10px;
  color: #333;
  text-decoration: none;
  font-weight: 600;
}
.content {
  width: 90%;
  background: white;
  border: 3px solid #ffd966;
  border-radius: 25px;
  padding: 20px;
  text-align: center;
}
.section-title {
  color: #003366;
  font-size: 18px;
  text-decoration: underline;
}
.materiels {
  display: flex;
  flex-direction: column;
  gap: 20px;
  margin-top: 15px;
}
.materiel-card {
  display: flex;
  align-items: center;
  border: 2px solid #a4e26a;
  border-radius: 15px;
  padding: 10px;
  background: #fffef8;
}
.materiel-image {
  width: 120px;
  height: 90px;
  border-radius: 10px;
  margin-right: 15px;
}
.quantity {
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 5px 0;
}
.quantity button {
  background: #6ab04c;
  color: white;
  border: none;
  padding: 4px 10px;
  border-radius: 5px;
  cursor: pointer;
  font-size: 18px;
}
.quantity input {
  width: 50px;
  text-align: center;
  border: 1px solid #ccc;
  border-radius: 5px;
  margin: 0 5px;
}
.btn-action {
  background: #6ab04c;
  color: white;
  border: none;
  padding: 8px 12px;
  border-radius: 8px;
  margin-top: 8px;
  cursor: pointer;
}
.btn-action.selected {
  background: #ffd966;
  color: #333;
}
.actions {
  display: flex;
  justify-content: center;
  gap: 15px;
  margin-top: 20px;
}
.btn-valid {
  background: #6ab04c;
  color: white;
  padding: 10px 15px;
  border: none;
  border-radius: 10px;
  font-weight: 600;
}
.btn-cancel {
  background: #ffd966;
  color: #333;
  padding: 10px 15px;
  border: none;
  border-radius: 10px;
  font-weight: 600;
}
.btn-logout {
  background: #a4e26a;
  border: none;
  margin-top: 15px;
  padding: 8px 15px;
  border-radius: 10px;
  color: #fff;
}
.footer {
  background: #ffd966;
  width: 100%;
  text-align: center;
  padding: 10px 0;
  margin-top: 20px;
  border-radius: 0 0 20px 20px;
}
</style>

// app/(tabs)/NosMateriels.tsx
import AsyncStorage from "@react-native-async-storage/async-storage";
import { useRouter } from "expo-router";
import React, { useState } from "react";
import {
  Alert,
  Image,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";

export default function NosMateriels() {
  const router = useRouter();

  const [materiels, setMateriels] = useState([
    {
      id: 1,
      nom: "Microphone sans fil professionnel",
      description: "Micro haute qualité adapté aux conférences et fêtes",
      prix: "10 000",
      quantite: 10,
      qteChoisie: 0,
      selectionne: false,
      image: require("../../assets/images/micro.jpg"),
    },
    {
      id: 2,
      nom: "Chaises blanches harmonieuses",
      description: "Confortables, idéales pour mariage et réception",
      prix: "2 000",
      quantite: 400,
      qteChoisie: 0,
      selectionne: false,
      image: require("../../assets/images/chaise.jpg"),
    },
    {
      id: 3,
      nom: "Table ronde et 6 places",
      description: "Tables élégantes, style dégagé",
      prix: "4 000",
      quantite: 200,
      qteChoisie: 0,
      selectionne: false,
      image: require("../../assets/images/table.jpg"),
    },
    {
      id: 4,
      nom: "Sonorisation complète",
      description: "Enceintes, mixeur, micro, tout le nécessaire musical",
      prix: "50 000",
      quantite: 5,
      qteChoisie: 0,
      selectionne: false,
      image: require("../../assets/images/sono.jpg"),
    },
  ]);

  // ➕ quantité
  const increment = (id: number) => {
    setMateriels((prev) =>
      prev.map((m) =>
        m.id === id && m.qteChoisie < m.quantite
          ? { ...m, qteChoisie: m.qteChoisie + 1 }
          : m
      )
    );
  };

  // ➖ quantité
  const decrement = (id: number) => {
    setMateriels((prev) =>
      prev.map((m) =>
        m.id === id && m.qteChoisie > 0
          ? { ...m, qteChoisie: m.qteChoisie - 1 }
          : m
      )
    );
  };

  // sélection
  const toggleSelection = (id: number) => {
    setMateriels((prev) =>
      prev.map((m) =>
        m.id === id ? { ...m, selectionne: !m.selectionne } : m
      )
    );
  };

  // ✅ VALIDER + AsyncStorage
  const valider = async () => {
    const selection = materiels.filter(
      (m) => m.selectionne && m.qteChoisie > 0
    );

    if (selection.length === 0) {
      Alert.alert(
        "Erreur",
        "Veuillez sélectionner au moins un matériel avec une quantité > 0"
      );
      return;
    }

    try {
      await AsyncStorage.setItem(
        "materielsSelectionnes",
        JSON.stringify(selection)
      );

      router.push("/reservation");
    } catch (error) {
      Alert.alert("Erreur", "Impossible de sauvegarder les matériels");
    }
  };

  // ❌ annuler
  const annuler = () => {
    setMateriels((prev) =>
      prev.map((m) => ({ ...m, qteChoisie: 0, selectionne: false }))
    );
    Alert.alert("Annulé", "Sélection annulée");
  };

  return (
    <ScrollView style={styles.page} contentContainerStyle={{ alignItems: "center" }}>
      {/* HEADER */}
      <View style={styles.header}>
        <View style={styles.logoSection}>
          <Image
            source={require("../../assets/images/logo.png")}
            style={styles.logo}
          />
          <Text style={styles.siteTitle}>Rêve d’un Jour</Text>
        </View>
      </View>

      {/* CONTENT */}
      <View style={styles.content}>
        <Text style={styles.sectionTitle}>
          CHOISISSEZ VOS MATÉRIELS
        </Text>

        {materiels.map((m) => (
          <View
            key={m.id}
            style={[
              styles.materielCard,
              m.selectionne && styles.selectedCard,
            ]}
          >
            <Image source={m.image} style={styles.materielImage} />

            <View style={styles.materielInfo}>
              <Text><Text style={{ fontWeight: "bold" }}>Nom :</Text> {m.nom}</Text>
              <Text><Text style={{ fontWeight: "bold" }}>Description :</Text> {m.description}</Text>
              <Text><Text style={{ fontWeight: "bold" }}>Prix :</Text> {m.prix} Ar</Text>
              <Text><Text style={{ fontWeight: "bold" }}>Disponible :</Text> {m.quantite}</Text>

              {/* Quantité */}
              <View style={styles.quantity}>
                <TouchableOpacity
                  style={styles.qteButton}
                  onPress={() => decrement(m.id)}
                >
                  <Text style={styles.qteTextBtn}>−</Text>
                </TouchableOpacity>

                <Text style={styles.qteText}>{m.qteChoisie}</Text>

                <TouchableOpacity
                  style={styles.qteButton}
                  onPress={() => increment(m.id)}
                >
                  <Text style={styles.qteTextBtn}>+</Text>
                </TouchableOpacity>
              </View>

              <TouchableOpacity
                style={[
                  styles.btnAction,
                  m.selectionne && styles.selectedButton,
                ]}
                onPress={() => toggleSelection(m.id)}
              >
                <Text style={styles.btnActionText}>
                  {m.selectionne ? "Sélectionné ✅" : "Sélectionner"}
                </Text>
              </TouchableOpacity>
            </View>
          </View>
        ))}

        {/* ACTIONS */}
        <View style={styles.actions}>
          <TouchableOpacity style={styles.btnValid} onPress={valider}>
            <Text style={{ color: "#fff", fontWeight: "bold" }}>
              Valider
            </Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.btnCancel} onPress={annuler}>
            <Text style={{ fontWeight: "bold" }}>Annuler</Text>
          </TouchableOpacity>
        </View>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: "#fff9e9" },
  header: { marginTop: 20 },
  logoSection: { flexDirection: "row", alignItems: "center", gap: 10 },
  logo: { width: 50, height: 50, borderRadius: 25 },
  siteTitle: { fontSize: 20, fontWeight: "bold", color: "#d93025" },

  content: {
    width: "90%",
    backgroundColor: "#fff",
    borderColor: "#ffd966",
    borderWidth: 3,
    borderRadius: 25,
    padding: 20,
    marginTop: 15,
  },

  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 15,
    color: "#003366",
  },

  materielCard: {
    flexDirection: "row",
    borderWidth: 2,
    borderColor: "#a4e26a",
    borderRadius: 15,
    padding: 10,
    marginBottom: 15,
    backgroundColor: "#fffef8",
  },

  selectedCard: {
    borderColor: "#ffd966",
    borderWidth: 3,
  },

  materielImage: {
    width: 120,
    height: 90,
    borderRadius: 10,
    marginRight: 10,
    resizeMode: "contain",
  },

  materielInfo: { flex: 1 },

  quantity: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 6,
  },

  qteButton: {
    backgroundColor: "#6ab04c",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 5,
  },

  qteTextBtn: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  qteText: { marginHorizontal: 10, fontWeight: "bold" },

  btnAction: {
    backgroundColor: "#6ab04c",
    padding: 8,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 5,
  },

  selectedButton: { backgroundColor: "#ffd966" },

  btnActionText: { color: "#fff", fontWeight: "bold" },

  actions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },

  btnValid: {
    backgroundColor: "#6ab04c",
    flex: 1,
    padding: 10,
    borderRadius: 10,
    alignItems: "center",
  },

  btnCancel: {
    backgroundColor: "#ffd966",
    flex: 1,
    padding: 10,
    borderRadius: 10,
    alignItems: "center",
  },
});
