// src/components/Reservation.vue
<template>
  <div class="page">
    <header class="header">
      <div class="logo-section">
        <img src="../assets/logo.jpg" class="logo" />
        <h1 class="site-title">Reve d' un Jour</h1>
      </div>
    </header>

    <main class="content">
      <h2 class="section-title">FINALISER VOTRE RÉSERVATION</h2>

      <!-- Salle choisie -->
      <div v-if="salle" class="info-block">
        <h3>Salle choisie :</h3>
        <p><b>Nom :</b> {{ salle.nom }}</p>
        <p><b>Capacité :</b> {{ salle.capacite }} personnes</p>
        <p><b>Prix :</b> {{ salle.prix }} Ar</p>
      </div>

      <!-- Matériel -->
      <div v-if="materiels.length > 0" class="info-block">
        <h3>Matériels sélectionnés :</h3>
        <ul>
          <li v-for="(m,i) in materiels" :key="i">
            {{ m.nom }} - {{ m.qteChoisie }} unité(s) - {{ m.prix }} Ar/unité
          </li>
        </ul>
      </div>

      <!-- Total -->
      <div class="total">
        <p><b>Total général : </b> {{ total }} Ar</p>
      </div>

      <!-- Date et heure -->
      <div class="date-input">
        <label>Date :</label>
        <input type="date" v-model="date" />

        <label>Heure de début :</label>
        <input type="time" v-model="heureDebut" />

        <label>Heure de fin :</label>
        <input type="time" v-model="heureFin" />
      </div>

      <!-- Actions -->
      <div class="actions">
        <button class="btn-valid" @click="confirmer">Confirmer ma réservation ✅</button>
        <router-link to="/NosOffres" class="btn-cancel">Modifier ma sélection</router-link>
      </div>

      <router-link to="/" class="btn-logout">Se déconnecter</router-link>
    </main>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import { useRouter } from "vue-router";

const salle = ref(null);
const materiels = ref([]);
const total = ref(0);
const date = ref("");
const heureDebut = ref("");
const heureFin = ref("");

const router = useRouter();

// Récupération des données depuis LocalStorage
onMounted(() => {
  salle.value = JSON.parse(localStorage.getItem("salleChoisie"));
  materiels.value = JSON.parse(localStorage.getItem("materielsSelectionnes")) || [];

  total.value = 0;
  if (salle.value) total.value += parseInt(salle.value.prix.replace(/\s/g,""));

  materiels.value.forEach(m => {
    total.value += m.qteChoisie * parseInt(m.prix.replace(/\s/g,""));
  });
});

// Confirmer la réservation et rediriger vers la page confirmation
function confirmer() {
  if (!date.value || !heureDebut.value || !heureFin.value) {
    return alert("Veuillez remplir la date et les heures !");
  }

  // Stocker les dates et heures pour la page confirmation
  localStorage.setItem("dateReservation", date.value);
  localStorage.setItem("heureDebutReservation", heureDebut.value);
  localStorage.setItem("heureFinReservation", heureFin.value);

  // Redirection vers la page confirmation
  router.push("/confirmation");
}
</script>

<style scoped>
.page {
  background:#fff9e9;
  min-height:100vh;
  text-align:center;
  font-family: "Poppins", sans-serif;
}

.logo-section {
  display: flex;
  flex-direction: column; /* Apetraka ambanin'ny logo ny soratra */
  align-items: center;    /* Apivony tsara eo afovoany */
}

.logo {
  width: 80px;   /* Ataovy lehibe kokoa raha tiana */
  height: 80px;
  border-radius: 50%;
}

.site-title {
  color: #d93025;
  font-weight: bold;
  font-size: 24px; /* Somary lehibe kely */
  margin-top: 10px; /* Misy elanelana kely eo ambanin'ny logo */
  text-align: center;
}

.header {
  display: flex;
  justify-content: center; /* Apivony eo afovoany ny rehetra */
  align-items: center;
  padding: 15px;
  border-bottom: 2px solid #ffd966;
  background: #fffef8;
}


.content {
  background:white;
  border:3px solid #ffd966;
  margin:20px auto;
  padding:20px;
  border-radius:25px;
  max-width:1000px;
}

.info-block {
  background:#fffef8;
  border:2px solid #a4e26a;
  padding:10px;
  margin-bottom:10px;
  border-radius:10px;
  text-align:left;
}

.total {
  font-size:18px;
  margin:10px 0;
}

.date-input input {
  margin:5px;
  padding:5px;
  width:200px;
}

.btn-valid {
  background:#6ab04c;
  color:white;
  padding:10px 15px;
  border-radius:10px;
  margin-top:10px;
  border:none;
  cursor:pointer;
}

.btn-cancel {
  background:#ffd966;
  padding:10px;
  border-radius:10px;
  margin-top:10px;
  display:inline-block;
  text-decoration:none;
  color:#333;
}
.btn-logout {
  margin-top:10px;
  display: inline-block;  
  color: white;
  background: #e74c3c;
  padding: 5px 12px;       
  border-radius: 10px;
  text-decoration: none;
  font-size: 14px;         
}


</style>

// app/(tabs)/reservation.tsx
import AsyncStorage from "@react-native-async-storage/async-storage";
import { useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import {
  Alert,
  Image,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";

interface Materiel {
  nom: string;
  qteChoisie: number;
  prix: string;
}

interface Salle {
  nom: string;
  capacite: number;
  prix: string;
}

export default function Reservation() {
  const router = useRouter();

  const [salle, setSalle] = useState<Salle | null>(null);
  const [materiels, setMateriels] = useState<Materiel[]>([]);
  const [total, setTotal] = useState<number>(0);
  const [date, setDate] = useState<string>("");
  const [heureDebut, setHeureDebut] = useState<string>("");
  const [heureFin, setHeureFin] = useState<string>("");

  // 🔹 Charger données depuis AsyncStorage
  useEffect(() => {
    const loadData = async () => {
      try {
        const salleStr = await AsyncStorage.getItem("salleChoisie");
        const materielsStr = await AsyncStorage.getItem("materielsSelectionnes");

        const salleData = salleStr ? JSON.parse(salleStr) : null;
        const materielsData: Materiel[] = materielsStr ? JSON.parse(materielsStr) : [];

        setSalle(salleData);
        setMateriels(materielsData);

        // Calcul total
        let t = 0;
        if (salleData) t += parseInt(salleData.prix.replace(/\s/g, ""));
        materielsData.forEach((m) => {
          t += m.qteChoisie * parseInt(m.prix.replace(/\s/g, ""));
        });
        setTotal(t);
      } catch (e) {
        Alert.alert("Erreur", "Impossible de charger les données de réservation");
        console.log(e);
      }
    };
    loadData();
  }, []);

  // 🔹 Confirmer réservation
  const confirmer = async () => {
    if (!date || !heureDebut || !heureFin) {
      Alert.alert("Erreur", "Veuillez remplir la date et les heures !");
      return;
    }

    try {
      await AsyncStorage.setItem("dateReservation", date);
      await AsyncStorage.setItem("heureDebutReservation", heureDebut);
      await AsyncStorage.setItem("heureFinReservation", heureFin);

      Alert.alert("✅ Succès", "Réservation confirmée !");
      router.push("/confirmation"); // Page de confirmation
    } catch (e) {
      Alert.alert("Erreur", "Impossible de sauvegarder la réservation");
    }
  };

  return (
    <ScrollView contentContainerStyle={styles.page}>
      {/* HEADER */}
      <View style={styles.header}>
        <Image source={require("../../assets/images/logo.png")} style={styles.logo} />
        <Text style={styles.siteTitle}>Rêve d’un Jour</Text>
      </View>

      <View style={styles.content}>
        <Text style={styles.sectionTitle}>FINALISER VOTRE RÉSERVATION</Text>

        {/* Salle choisie */}
        {salle && (
          <View style={styles.infoBlock}>
            <Text style={styles.subTitle}>Salle choisie :</Text>
            <Text><Text style={{ fontWeight: "bold" }}>Nom :</Text> {salle.nom}</Text>
            <Text><Text style={{ fontWeight: "bold" }}>Capacité :</Text> {salle.capacite} personnes</Text>
            <Text><Text style={{ fontWeight: "bold" }}>Prix :</Text> {salle.prix} Ar</Text>
          </View>
        )}

        {/* Matériels */}
        {materiels.length > 0 && (
          <View style={styles.infoBlock}>
            <Text style={styles.subTitle}>Matériels sélectionnés :</Text>
            {materiels.map((m, i) => (
              <Text key={i}>
                {m.nom} - {m.qteChoisie} unité(s) - {m.prix} Ar/unité
              </Text>
            ))}
          </View>
        )}

        {/* Total */}
        <View style={styles.total}>
          <Text><Text style={{ fontWeight: "bold" }}>Total général :</Text> {total} Ar</Text>
        </View>

        {/* Date et heure */}
        <View style={styles.dateInput}>
          <Text>Date :</Text>
          <TextInput
            placeholder="YYYY-MM-DD"
            style={styles.input}
            value={date}
            onChangeText={setDate}
          />

          <Text>Heure de début :</Text>
          <TextInput
            placeholder="HH:MM"
            style={styles.input}
            value={heureDebut}
            onChangeText={setHeureDebut}
          />

          <Text>Heure de fin :</Text>
          <TextInput
            placeholder="HH:MM"
            style={styles.input}
            value={heureFin}
            onChangeText={setHeureFin}
          />
        </View>

        {/* Actions */}
        <View style={styles.actions}>
          <TouchableOpacity style={styles.btnValid} onPress={confirmer}>
            <Text style={{ color: "#fff", fontWeight: "bold" }}>Confirmer ma réservation ✅</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.btnCancel} onPress={() => router.push("/NosOffres")}>
            <Text style={{ fontWeight: "bold" }}>Modifier ma sélection</Text>
          </TouchableOpacity>
        </View>

        <TouchableOpacity style={styles.btnLogout} onPress={() => router.push("/")}>
          <Text style={{ color: "#fff", fontWeight: "bold" }}>Se déconnecter</Text>
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  page: { backgroundColor: "#fff9e9", alignItems: "center", paddingVertical: 20 },
  header: { alignItems: "center", marginBottom: 15 },
  logo: { width: 80, height: 80, borderRadius: 40, marginBottom: 10 },
  siteTitle: { fontSize: 24, fontWeight: "bold", color: "#d93025" },
  content: { backgroundColor: "#fff", borderWidth: 3, borderColor: "#ffd966", borderRadius: 25, padding: 20, width: "90%" },
  sectionTitle: { fontSize: 18, fontWeight: "bold", color: "#003366", textAlign: "center", marginBottom: 10 },
  infoBlock: { backgroundColor: "#fffef8", borderWidth: 2, borderColor: "#a4e26a", borderRadius: 10, padding: 10, marginBottom: 10 },
  subTitle: { fontWeight: "bold", marginBottom: 5 },
  total: { fontSize: 18, marginVertical: 10 },
  dateInput: { marginVertical: 10 },
  input: { borderWidth: 1, borderColor: "#ccc", borderRadius: 5, padding: 5, marginVertical: 5, width: "100%" },
  actions: { flexDirection: "row", justifyContent: "space-between", marginTop: 10 },
  btnValid: { backgroundColor: "#6ab04c", padding: 10, borderRadius: 10, flex: 1, marginRight: 5, alignItems: "center" },
  btnCancel: { backgroundColor: "#ffd966", padding: 10, borderRadius: 10, flex: 1, marginLeft: 5, alignItems: "center" },
  btnLogout: { marginTop: 15, backgroundColor: "#e74c3c", padding: 8, borderRadius: 10, alignItems: "center" },
});
